### ISSUE TITLE
Add tunneling (per server)

### ISSUE THREAD

**Issue by JosuaKrause** [JosuaKrause/parcell#5]
Use https://github.com/paramiko/paramiko/blob/master/demos/forward.py
and
https://github.com/VisTrails/tej/issues/18 as resource

**Comment by JosuaKrause** [comment]
Preliminary work in 13dd60a5293cf165c160de2c53510b60b9435dca
Main problem is known_host acceptance for `localhost`/`127.0.0.1`
Also it might be worth just executing `ssh -L ...` instead of emulating it in python.

**Comment by remram44** [comment]
You can provide a MissingHostKeyPolicy to paramiko to get it to do whatever when the key is not in `known_hosts`, for example ignore the issue (when the hostname is localhost?)

See [reprounzip-vagrant's run_interactive()](https://github.com/ViDA-NYU/reprozip/blob/506bf0ed2d41f1bc1dd9a77bde17745bb6b1fd3f/reprounzip-vagrant/reprounzip/unpackers/vagrant/run_command.py#L141)

**Comment by JosuaKrause** [comment]
The policy is fixed for tej (would need to implement a way to change that).
But yeah -- that's what I used for testing.
However, it's quite a big jump to go from security doesn't work in special case (even if it's an important one) to no security at all :/

**Comment by remram44** [comment]
You can implement a better MissingHostKeyPolicy that looks up the key with the correct (non-tunneled) address in the system HostKeys, since paramiko has an API to load and compare those.

I can offer the SSHClient creation for override if that makes sense:
```diff
--- a/tej/submission.py
+++ b/tej/submission.py
@@ -290,17 +290,24 @@ class RemoteQueue(object):
     def destination_string(self):
         return destination_as_string(self.destination)

+    def _ssh_client(self):
+        """Gets an SSH client to connect with.
+        """
+        ssh = paramiko.SSHClient()
+        ssh.load_system_host_keys()
+        ssh.set_missing_host_key_policy(paramiko.RejectPolicy())
+        return ssh
+
     def _connect(self):
         """Connects via SSH.
         """
-        self._ssh = paramiko.SSHClient()
-        self._ssh.load_system_host_keys()
-        self._ssh.set_missing_host_key_policy(paramiko.RejectPolicy())
+        ssh = self._ssh_client()
         logger.debug("Connecting with %s",
                      ', '.join('%s=%r' % (k, v if k != "password" else "***")
                                for k, v in iteritems(self.destination)))
-        self._ssh.connect(**self.destination)
+        ssh.connect(**self.destination)
         logger.debug("Connected to %s", self.destination['hostname'])
+        self._ssh = ssh

     def get_client(self):
         """Gets the SSH client.
```

**Comment by JosuaKrause** [comment]
That might actually be better than my pull request -- you decide.
EDIT: updated the pull request to your approach

**Comment by remram44** [comment]
Committed as [`ec0d27d2`](https://github.com/VisTrails/tej/commit/ec0d27d21fb3fc6a4a7c8622843904870c7d9256).
