### ISSUE TITLE
Properly look up tunneled host keys

### ISSUE THREAD

**Issue by JosuaKrause** [JosuaKrause/parcell#8]
See [here](https://github.com/JosuaKrause/parcell/issues/5#issuecomment-267154019) for further explanation.

**Comment by remram44** [comment]
I'm going with ec0d27d2 instead, allowing the user to override the SSHClient creation. This way you can customize know_hosts lists and missing key policy.

**Comment by JosuaKrause** [comment]
Also prompt the user yes/no if encountering an actual unknown key...

[reference for policy implementation](https://github.com/ViDA-NYU/reprozip/blob/506bf0ed2d41f1bc1dd9a77bde17745bb6b1fd3f/reprounzip-vagrant/reprounzip/unpackers/vagrant/run_command.py#L26)
