### ISSUE TITLE
Use pexpect for tunnel

### ISSUE THREAD

**Issue by JosuaKrause** [JosuaKrause/parcell#9]
ssh asks for password even when provided with one through stdin on some systems. pexpect should solve this issue.

https://github.com/pexpect/pexpect/blob/master/examples/ssh_tunnel.py

This would speed up the authentication process a lot (otherwise you need to type your password for every tunnel server)

**Comment by remram44** [comment]
Or just use keys! Also there's Python [pexpect](https://github.com/pexpect/pexpect), terminal [expect](http://expect.sourceforge.net/), and [sshpass](https://linux.die.net/man/1/sshpass)
